### PR TITLE
Noarch build to incorporate ppc64le

### PR DESCRIPTION
**Pull request by SC426**
ca-certificates 2023.12.12

**Destination channel:** defaults

### Links

- [PKG-3836](https://anaconda.atlassian.net/browse/PKG-3836)
- [Upstream repository]()

### Explanation of changes:

- Make noarch
- Raise build number
- skip missing_section lint

[PKG-3836]: https://anaconda.atlassian.net/browse/PKG-3836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by danpetry — APPROVED** [review]

**Review by chenghlee — COMMENTED** [review]
I'm not sure if noarch is actually going to work; if you look in the Windows `bld.bat`, the cacert.pem ends up in `$PREFIX\Library\ssl`, while on \*nix (`build.sh`), `cacert.pem` ends up in `$PREFIX\ssl`. Making this recipe noarch is very likely going to break either Windows or \*nix.

**Comment by danpetry** [comment]
Is there an easy way of cross-"compiling"?

**Comment by chenghlee** [comment]
Not sure. `noarch: generic  # [unix]` might work, but even if it does, that just reeks of code smell.

**Comment by cbouss** [comment]
> I'm not sure if noarch is actually going to work; if you look in the Windows `bld.bat`, the cacert.pem ends up in `$PREFIX\Library\ssl`, while on *nix (`build.sh`), `cacert.pem` ends up in `$PREFIX\ssl`. Making this recipe noarch is very likely going to break either Windows or *nix.

Ah right, I overlooked that. The intent was to have a friendly ppc package for future updates. 
noarch + selectors and dependency on __win would work, but it does add complexity. 
We can build this for ppc as a one off.

**Comment by SC426** [comment]
@Callek Could you help kick off a ppc build for this PR?

**Comment by Callek** [comment]
> @Callek Could you help kick off a ppc build for this PR?

No, per @remkade we removed that possibility from our previous PPC system.  Tucker was planning to disable its NIC and shut it down this week as well.

**Comment by cbouss** [comment]
> > @Callek Could you help kick off a ppc build for this PR?
> 
> No, per @remkade we removed that possibility from our previous PPC system. Tucker was planning to disable its NIC and shut it down this week as well.

@SC426 we can make a manual build

**Comment by danpetry** [comment]
`CONDA_SUBDIR=linux-ppc64le conda build ca-certificates-feedstock/`?

**Pull request closed without merging**
